// resources/js/templates/signTemplates.js
import {materials} from '@/materials/materialTypes';
//material.Application types: illum,back_illum,int_printed,ext_cutltr,int_cutltr
const material = materials;

export const signTemplates = {
  "Wall Sign Illuminated": {
    template: "wall_illum",
    illuminated: true,
    code: "WALL_ILUM",
    face: {
      width: 71,
      height: 35,
      maxW: 191,
      maxH: 143,
      shape: "flat",
      materialOptions: material.Application.illum,
    },
    cabinet: {
      width: 72,
      height: 36,
      maxW: 192,
      maxH: 144,
      depth: 8,
      borderWidthInches: 1,
      material: ["polycarbonate"],
      fill: "#ffffff",
    },
    lighting: {
      type: "led",
      length: 72,
      uom: "inches",
      structure: "led",
      count: 2,
    },
    post: null,
  },
  "Wall Sign Exterior": {
    template: "wall_ext",
    illuminated: false,
    code: "WALL_EXT",
    face: {
      width: 72,
      height: 36,
      maxW: 192,
      maxH: 144,
      shape: "flat",
      materialOptions: material.Application.ext_printed,
    },
    cabinet: null,
    lighting: null,
    post: null,
  },
  "Wall Sign Interior": {
    template: "WALL_INT",
    illuminated: false,
    code: "WALL_INT",
    face: {
      width: 72,
      height: 36,
      maxW: 192,
      maxH: 144,
      shape: "flat",
      material: "int_printed",
    },
    cabinet: null,
    lighting: null,
    post: null,
  },
  "Pylon Illuminated Cabinet": {
    template: "pylon_illum",
    illuminated: true,
    code:"PYL_ILUM",
    face: {
      width: 71,
      height: 47,
      shape: "flat",
      materialOptions: material.Application.illum,
    },
    cabinet: {
      width: 72,
      height: 48,
      depth: 8,
      borderWidthInches: 1,
      material: "aluminum",
      fill: "#ffffff",
    },
    lighting: {
      type: "led",
      length: 48,
      uom: "inches",
      structure: "strand",
      count: 3,
    },
    post: {
      height: 12,
      uom: "feet",
      mount: "bottom",
      color: "#ffffff",
    },
  },

  "Pylon Non-Illuminated": {
    template: "pylon",
    illuminated: false,
    code:"PYL",
    face: {
      width: 71,
      height: 47,
      shape: "flat",
      materialOptions: material.Application.ext_printed,
    },
    cabinet: {
      width: 72,
      height: 47,
      depth: 8,
      mount: "post",
      borderWidthInches: 1,
      material: "steel",
      fill: "#ffffff",
    },
    lighting: null,
    post: {
      height: 120,
      uom: "feet",
      mount: "bottom",
      color: "#ffffff",
    },
  },

  "Monument Illuminated": {
    template: "monument_illum",
    illuminated: true,
    code:"MON_ILUM",
    face: {
      width: 71,
      height: 35,
      shape: "flat",
      materialOptions: material.Application.illum,
    },
    cabinet: {
      width: 72,
      height: 36,
      depth: 8,
      borderWidthInches: 1,
      material: "aluminum",
      color: "#ffffff",
    },
    lighting: {
      type: "neon tube",
      length: 36,
      uom: "inches",
      structure: "tube",
      count: 2,
    },
    post: {
      height: 5,
      uom: "feet",
      mount: "bottom",
      color: "#ffffff",
    },
  },
  "Monument": {
    template: "monument",
    illuminated: false,
    code:"MON",
    face: {
      width: 72,
      height: 36,
      shape: "flat",
      materialOptions: material.Application.ext_printed,
    },
    cabinet: {
      width: 72,
      height: 36,
      depth: 8,
      borderWidthInches: 1,
      material: "steel",
      color: "#ffffff",
    },
    lighting: null,
    post: {
      height: 3,
      mount: "bottom",
      color: "#ffffff",
    },
  },
  "Channel Letters": {
    template: "channel_letters",
    illuminated: true,
     code: "CHN_LTR",
    face: {
      width: 72,
      height: 24,
      shape: "flat",
      materialOptions: material.Application.illum,
    },
    cabinet: {
      width: null,
      height: null,
      depth: 8,
      borderWidthInches: null,
      material: "aluminum",
      color: "#ffffff",
    },
    lighting: {
      type: "led",
      length: "NA",
      uom: "inches",
      structure: "strand",
      count: 3,
    },
    post: null,
  },
  "Cut Letters Interior": {
    template: "cut_ltrs",
    illuminated: false,
    code: "CUT_LTR_INT",
    face: {
      width: 72,
      height: 36,
      shape: "flat",
      materialOptions: material.Application.int_cutltr,
    },
    cabinet: null,
    lighting: null,
    post: null,
  },
  "Cut Letters Exterior": {
    template: "cut_ltrs",
    illuminated: false,
    code: "CUT_LTR_EXT",
    face: {
      width: 72,
      height: 36,
      shape: "flat",
      materialOptions: material.Application.ext_cutltr,
    },
    cabinet: null,
    lighting: null,
    post: null,
  },
  "Face Replacement": {
    template: "face_replacement",
    illuminated: false,
    code: "FR",
    face: {
      width: 72,
      height: 36,
      shape: "flat",
      materialOptions: material.Application.ext_printed,
    },
    cabinet: null,
    lighting: null,
    post: null,
  },
  "Face Replacement Illuminated": {
    template: "face_replacement",
    illuminated: true,
    code: "FR_ILUM",
    face: {
      width: 72,
      height: 36,
      shape: "custom",
      materialOptions: material.Application.illum,
    },
    cabinet: null,
    lighting: null,
    post: null,
  },
};
